# Generated by Django 4.2.3 on 2023-07-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="counted_view",
            field=models.IntegerField(default=0),
        ),
    ]
