# Generated by Django 4.2.3 on 2023-08-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_category_post_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="category",
            new_name="post_category",
        ),
    ]
